WINE_GLOSSARY = {
    # Основные термины
    "Red wine": "Красное вино",
    "White wine": "Белое вино",
    "Rosé wine": "Розовое вино",
    "Sparkling wine": "Игристое вино",
    "Dessert wine": "Десертное вино",
    "Fortified Wine": "Креплёное вино",


    # Вкусовой профиль
    "Light - Bold": "Лёгкое — Насыщенное",
    "Smooth - Tannic": "Мягкое — Танинное",
    "Dry - Sweet": "Сухое — Сладкое",
    "Soft - Acidic": "Мягкое — Кислотное",

    # Light - Bold (Лёгкое — Насыщенное)
    "Completely light": "Абсолютно лёгкое",
    "Mostly light, but with a slight tendency": "Скорее лёгкое, но с небольшим уклоном",
    "A bit closer to light, but almost balanced": "Ближе к лёгкому, но почти сбалансированное",
    "Completely bold": "Абсолютно насыщенное",
    "Mostly bold, pronounced": "Ярко выраженное насыщенное",
    "Slightly bold, but still moderate": "Умеренно насыщенное",

    # Dry - Sweet (Сухое — Сладкое)
    "Completely dry": "Абсолютно сухое",
    "Mostly dry, but with a slight tendency": "Преимущественно сухое с легкой сладостью",
    "A bit closer to dry, but almost balanced": "Ближе к сухому, но почти сбалансированное",
    "Completely sweet": "Абсолютно сладкое",
    "Mostly sweet, pronounced": "Ярко выраженное сладкое",
    "Slightly sweet, but still moderate": "Умеренно сладкое",

    # Soft - Acidic (Мягкое — Кислотное)
    "Completely soft": "Абсолютно мягкое",
    "Mostly soft, but with a slight tendency": "Преимущественно мягкое с легкой кислотностью",
    "A bit closer to soft, but almost balanced": "Ближе к мягкому, но почти сбалансированное",
    "Completely acidic": "Ярко выраженное кислотное",
    "Mostly acidic, pronounced": "Преимущественно кислотное",
    "Slightly acidic, but still moderate": "Умеренно кислотное",

    # Smooth - Tannic (Мягкое — Танинное)
    "Completely smooth": "Исключительно мягкое",
    "Mostly smooth, but with a slight tendency": "Преимущественно мягкое, с лёгкой танинностью",
    "A bit closer to smooth, but almost balanced": "Ближе к мягкому, но с заметными танинами",
    "Completely tannic": "Очень танинное",
    "Mostly tannic, pronounced": "Ярко выраженное танинное",
    "Slightly tannic, but still moderate": "Умеренно танинное",

    # Gentle - Fizzy (Нежное — Игристое)
    "Gentle - Fizzy": "Нежное — Игристое",
    "Completely gentle": "Абсолютно нежное",
    "Mostly gentle, but with a slight tendency": "Преимущественно нежное с лёгким намёком на игристость",
    "A bit closer to gentle, but almost balanced": "Ближе к нежному, но почти сбалансированное",
    "Slightly fizzy, but still moderate": "Умеренно игристое",
    "Mostly fizzy, pronounced": "Ярко выраженное игристое",
    "Completely fizzy": "Сильноигристое (газированное)",

    "Balanced": "Сбалансированное",


    # Ноты
    "oaky": "Дубовые ноты",
    "black fruit": "Тёмные фрукты",
    "red fruit": "Красные фрукты",
    "tree fruit": "Фруктовые ноты",
    "citrus": "Цитрусовые ноты",
    "earthy": "Землистые ноты",
    "spices": "Пряные ноты",
    "dried fruit": "Сухофрукты",
    "floral": "Цветочные ноты",
    "yeasty": "Дрожжевые ноты",
    "tropical": "Экзотические ноты",
    "vegetal": "Зеленые тона",
    "ageing": "Ноты выдержки",

    # Дубовые ноты
    "oak": "дуб",
    "vanilla": "ваниль",
    "cedar": "кедр",
    "cigar box": "сигарная коробка",
    "hickory": "гикори (ореховое дерево)",
    "wood smoke": "древесный дым",
    "tobacco": "табак",
    "sweet tobacco": "сладкий табак",
    "cigar": "сигара",
    "chocolate": "шоколад",
    "dark chocolate": "тёмный шоколад",
    "milk chocolate": "молочный шоколад",
    "mocha": "мокко",
    "fudge": "помадка",
    "butterscotch": "ириска",
    "coffee": "кофе",
    "espresso": "эспрессо",
    "clove": "гвоздика",
    "nutmeg": "мускатный орех",
    "allspice": "душистый перец",
    "baking spice": "выпечные специи",
    "camphor": "камфара",
    "dill": "укроп",
    "caramel": "карамель",
    "toffee": "ириска",
    "butter": "сливочность",
    "coconut": "кокос",
    "cola": "кола",

    # Тёмные фрукты
    "plum": "слива",
    "dark fruit": "тёмные фрукты",
    "blackberry": "ежевика",
    "ripe blackberry": "спелая ежевика",
    "bramble": "ежевика (дикая)",
    "black plum": "чёрная слива",
    "blueberry": "черника",
    "bilberry": "черника (лесная)",
    "boysenberry": "бойзенова ягода",
    "mulberry": "шелковица",
    "black cherry": "чёрная вишня",
    "blackcurrant": "чёрная смородина",
    "cassis": "кассис (чёрная смородина)",
    "jam": "джем/варенье",
    "berry sauce": "ягодный соус",
    "acai berry": "ягода асаи",

    # Красные фрукты
    "cherry": "вишня",
    "raspberry": "малина",
    "strawberry": "клубника",
    "watermelon": "арбуз",
    "cherry cola": "вишнёвая кола",
    "red cherry": "красная вишня",
    "bing cherry": "вишня Бинг",
    "morello cherry": "вишня морелло",
    "sour cherry": "кислая вишня",
    "cherry syrup": "вишнёвый сироп",
    "ripe strawberry": "спелая клубника",
    "red currant": "красная смородина",
    "cranberry": "клюква",
    "red plum": "красная слива",
    "pomegranate": "гранат",

    # Деревенские/землистые ноты
    "leather": "кожа",
    "smoke": "дым",
    "honey": "мёд",
    "ginger": "имбирь",
    "forest floor": "лесная подстилка",
    "mushroom": "грибы",
    "truffle": "трюфель",
    "potting soil": "парниковая земля",
    "underbrush": "подлесок",
    "chalk": "мел",
    "minerals": "минеральные ноты",
    "flint": "кремень",
    "stone": "камень",
    "ash": "пепел",
    "graphite": "графит",
    "game": "дичь",
    "cured meat": "вяленое мясо",
    "barbecue meat": "мясо с гриля",
    "roasted meat": "жареное мясо",
    "grilled meat": "мясо на гриле",
    "pastrami": "пастрами",
    "barbecue smoke": "дым от барбекю",
    "tar": "дёготь",
    "tobacco leaf": "табачный лист",
    "balsamic": "ноты бальзамика",
    "exotic spice": "экзотические специи",
    "charcoal": "древесный уголь",
    "cocoa": "какао",
    "pencil shavings": "стружка карандаша",
    "pencil lead": "грифель карандаша",
    "salt": "соль",

    # Плодовые
    "peach": "персик",
    "melon": "дыня",
    "apricot": "абрикос",
    "apple": "яблоко",
    "green apple": "зелёное яблоко",
    "yellow apple": "жёлтое яблоко",
    "baked apple": "печёное яблоко",
    "bruised apple": "подгнившее яблоко",
    "pear": "груша",
    "asian pear": "азиатская груша",
    "white peach": "белый персик",
    "yellow peach": "жёлтый персик",
    "nectarine": "нектарин",
    "stewed apricot": "томлёный абрикос",
    "apricot jam": "абрикосовый джем",
    "stone fruit": "косточковые фрукты",
    "yellow plum": "жёлтая слива",
    "mirabelle plum": "мирабель",
    "quince": "айва",

    # Цитрусовые ноты
    "grapefruit": "грейпфрут",
    "lemon": "лимон",
    "lime": "лайм",
    "lime zest": "цедра лайма",
    "orange": "апельсин",
    "tangerine": "мандарин",

    # Ноты выдержки
    "brioche": "бриошь",
    "toast": "тост",
    "nutty": "ореховые ноты",
    "almond": "миндаль",
    "toasted almond": "жареный миндаль",
    "roasted almond": "жареный миндаль",
    "biscuit": "бисквит",
    "hazelnut": "фундук",
    "roasted hazelnut": "жареный фундук",
    "marzipan": "марципан",
    "walnut": "грецкий орех",
    "toasted nuts": "жареные орехи",
    "brown sugar": "коричневый сахар",
    "burnt sugar": "жжёный сахар",
    "chestnut": "каштан",
    "pecan": "пекан",
    "peanut": "арахис",
    "graham cracker": "грахем крекер",
    "maple syrup": "кленовый сироп",

    # Пряные ноты
    "licorice": "солодка",
    "black licorice": "чёрная солодка",
    "pepper": "перец",
    "white pepper": "белый перец",
    "cracked pepper": "молотый перец",
    "cinnamon": "корица",
    "dried herbs": "сушёные травы",
    "mint": "мята",
    "menthol": "ментол",
    "savory": "чабер",
    "eucalyptus": "эвкалипт",
    "anise": "анис",
    "thyme": "тимьян",
    "gingerbread": "имбирный пряник",
    "5-spice powder": "смесь 5 специй",
    "juniper": "можжевельник",
    "oregano": "орегано",
    "rosemary": "розмарин",
    "sage": "шалфей",

    # Зеленые тона
    "straw": "солома",
    "gooseberry": "крыжовник",
    "chard": "листовая свёкла",
    "grass": "трава",
    "fresh-cut grass": "свежескошенная трава",
    "hay": "сено",
    "asparagus": "спаржа",
    "bitter almond": "горький миндаль",
    "tomato": "помидор",
    "rhubarb": "ревень",

    # Цветочные ноты
    "elderflower": "бузина",
    "honeysuckle": "жимолость",
    "orange blossom": "цветок апельсина",
    "acacia": "акация",
    "jasmine": "жасмин",
    "apple blossom": "цветение яблони",
    "chamomile": "ромашка",
    "dried flowers": "сушеные цветы",
    "perfume": "парфюмерные ноты",
    "lily": "лилия",
    "violet": "фиалка",

    # Дрожжевые ноты
    "cream": "сливки",
    "yeast": "дрожжи",
    "cheese": "сыр",

    # Тропические ноты
    "pineapple": "ананас",
    "green pineapple": "зелёный ананас",
    "mango": "манго",
    "lychee": "личи",
    "passion fruit": "маракуйя",
    "guava": "гуава",
    "kiwi": "киви",
    "papaya": "папайя",
    "starfruit": "карамбола",

    # Сухофрукты
    "raisin": "изюм",
    "fig": "инжир",
    "prune": "чернослив",
    "black raisin": "чёрный изюм",
    "dried apricot": "курага",
    "dried cranberry": "сушёная клюква",
    "fruitcake": "фруктовый кекс",
    "dried blueberry": "сушеная черника",


    # Аллергены
    "Contains sulfites": "содержит сульфиты",
    "Contains sulfites, egg allergens, milk allergens": "содержит сульфиты, аллергены яиц и молока",


    #Базовая информация
    "Winery": "Винодельня",
    "Grapes": "Сорт винограда",
    "Region": "Регион",
    "Wine style": "Стиль вина",
    "Alcohol content": "Крепость",
    "Allergens": "Аллергены",


    # Гастрономические сочетания
    # Мясные блюда
    "Beef": "Говядина",
    "Lamb": "Баранина",
    "Pork": "Свинина",
    "Veal": "Телятина",
    "Game (deer, venison)": "Дичь (оленина, мясо оленя)",
    "Cured Meat": "Вяленое мясо",

    # Птица и другие
    "Poultry": "Птица",
    "Goat's Milk Cheese": "Козий сыр",

    # Рыба и морепродукты
    "Rich fish (salmon, tuna etc)": "Жирная рыба (лосось, тунец и др.)",
    "Lean fish": "Постная рыба",
    "Shellfish": "Моллюски",

    # Сыры
    "Mature and hard cheese": "Выдержанные твердые сыры",
    "Mild and soft cheese": "Мягкие молодые сыры",
    "Blue cheese": "Сыр с плесенью",

    # Остальное
    "Pasta": "Паста",
    "Mushrooms": "Грибы",
    "Vegetarian": "Вегетарианские блюда",
    "Spicy food": "Острая пища",

    # Десерты
    "Fruity desserts": "Фруктовые десерты",
    "Sweet desserts": "Сладкие десерты",

    # Аперитивы и закуски
    "Aperitif": "Аперитив",
    "Appetizers and snacks": "Закуски",
    "Any junk food will do": "Фаст-фуд",


    # Сорта винограда
    "Cabernet Sauvignon": "Каберне Совиньон",
    "Merlot": "Мерло",
    "Pinot Noir": "Пино Нуар",
    "Syrah": "Сира",
    "Shiraz": "Шираз",
    "Grenache": "Гренаш",
    "Tempranillo": "Темпранильо",
    "Malbec": "Мальбек",
    "Carmenere": "Карменер",
    "Zinfandel": "Зинфандель",
    "Petit Verdot": "Пти Вердо",
    "Cabernet Franc": "Каберне Фран",
    "Barbera": "Барбера",
    "Mourvèdre": "Мурведр",
    "Gamay": "Гамэ",
    "Chardonnay": "Шардоне",
    "Sauvignon Blanc": "Совиньон Блан",
    "Riesling": "Рислинг",
    "Pinot Gris": "Пино Гри",
    "Gewürztraminer": "Гевюрцтраминер",
    "Viognier": "Вионье",
    "Chenin Blanc": "Шенен Блан",
    "Semillon": "Семильон",
    "Muscat": "Мускат",
    "Albariño": "Альбариньо",
    "Grüner Veltliner": "Грюнер Вельтлинер",
    "Furmint": "Фурминт",
    "Blaufränkisch": "Блауфранкиш",
    "Kékfrankos": "Кекфранкош",
    "Kadarka": "Кадарка",
    "Plavac Mali": "Плавац Мали",
    "Vranac": "Вранац",
    "Saperavi": "Саперави",
    "Rkatsiteli": "Ркацители",
    "Mtsvane": "Мцване",
    "Kisi": "Киси",
    "Aglianico": "Альянико",
    "Nero d'Avola": "Неро д'Авола",
    "Xinomavro": "Ксиномавро",
    "Assyrtiko": "Асиртико",
    "Moschofilero": "Москофилера",
    "Mavrodaphne": "Мавродафни",
    "Macabeo": "Макабео",
    "Parellada": "Парельяда",
    "Xarel-lo": "Шарелло",
    "Touriga Nacional": "Турига Насьональ",
    "Tinta Roriz": "Тинта Рориш",
    "Baga": "Бага",
    "Vinhão": "Виньян",
    "Krasnostop": "Красностоп",
    "Tsimlyansky": "Цимлянский",
    "Siberian": "Сибирский",
    "Dostoyny": "Достойный",
    "Regent": "Регент",
    "Cabernet Cortis": "Каберне Кортис",
    "Solaris": "Соларис",
    "Tannat": "Таннат",
    "Graciano": "Грасиано",
    "Cinsault": "Сенсо",
    "Carignan": "Кариньян",
    "Marselan": "Марселан",
    "Petit Manseng": "Пти Мансенг",
    "Gros Manseng": "Гро Мансенг",
    "Poulsard": "Пульсар",
    "Trousseau": "Труссо",
    "Savagnin": "Саваньен",
    "Fiano": "Фьяно",
    "Greco": "Греко",
    "Falanghina": "Фалангина",
    "Pecorino": "Пекорино",
    "Arneis": "Арнеис",
    "Cortese": "Кортезе",
    "Erbaluce": "Эрбалуче",
    "Garganega": "Гарганега",
    "Trebbiano": "Треббьяно",
    "Verdicchio": "Вердиккио",
    "Montepulciano": "Монтепульчано",
    "Lagrein": "Лагрейн",
    "Teroldego": "Терольдего",
    "Schiava": "Скьява",
    "Dolcetto": "Дольчетто",
    "Freisa": "Фрейза",
    "Pelaverga": "Пелаверга",
    "Rossese": "Россезе",
    "Corvina": "Корвина",
    "Rondinella": "Рондинелла",
    "Molinaro": "Молинара",
    "Negroamaro": "Негроамаро",
    "Primitivo": "Примитиво",
    "Uva di Troia": "Ува ди Троя",
    "Bombino Nero": "Бомбино Неро",
    "Gaglioppo": "Гальоппо",
    "Magliocco": "Мальокко",
    "Nerello Mascalese": "Нерелло Маскалезе",
    "Nerello Cappuccio": "Нерелло Каппуччо",
    "Frappato": "Фраппато",
    "Perricone": "Периконе",
    "Susumaniello": "Сусуманиелло",
    "Bovale": "Бовале",
    "Cannonau": "Каннонау",
    "Carricante": "Карриканте",
    "Catarratto": "Катарратто",
    "Inzolia": "Инзолия",
    "Minnella": "Миннелла",
    "Nerello": "Нерелло",
    "Nocera": "Ночера",
    "Zibibbo": "Зибиббо",
    "Monastrell": "Монастрель",
    "Shiraz/Syrah": "Сира/Шираз",
    "Pinot Meunier": "Пино Менье",
    "Krasnostop Zolotovsky": "Красностоп Золотовский",
    "Sibirkovy": "Сибирьковый",
    "Tsimlyansky Black": "Цимлянский черный",
    "Plechistik": "Плечистик",
    "Rubinovy Magarach": "Рубиновый Магарач",
    "Golubok": "Голубок",
    "Kokur": "Кокур",
    "Saperavi Severny": "Саперави Северный",
    "Kaberne Severny": "Каберне Северный",
    "Citronny Magarach": "Цитронный Магарач",
    "Solnechny Magarach": "Солнечный Магарач",
    "Magarach 31-77": "Магарач 31-77",
    "Magarach Bastardo": "Магарач Бастардо",
    "Viorika": "Виорика",
    "Riton": "Ритон",
    "Crystal": "Кристалл",
    "Muscat Blanc": "Мускат Блан",
    "Muscat of Alexandria": "Мускат Александрии",
    "Muscat Ottonel": "Мускат Оттонель",
    "White Muscat": "Белый мускат",
    "Moscato Bianco": "Москато Бьянко",
    "Moscato Giallo": "Москато Джалло",
    "Moscato Rosa": "Москато Роза",
    "Torrontés": "Торронтес",
    "Malvasia Bianca": "Мальвазия Бьянка",
    "Blanc du Bois": "Блан дю Буа",
    "Muscardin": "Мюскарден",


    # Тип укупорки
    'Bottle closure': "Тип укупорки",
    "Cork": "Пробка",
    "Screwcap": "Винтовая крышка",
    "Synthetic cork": "Синтетическая пробка",
    "Glass stopper": "Стеклянная пробка",
    "Crown cap": "Кронпробка",
    "Helix": "Хеликс (винтовая пробка)",
    "Diam": "Диам (техническая пробка)",
    "Zork": "Зорк (комбинированная пробка)",
    "Vinolok": "Вино-лок (стеклянный замок)",
    "Rebo": "Ребо",
    "Pignolo": "Пиньоло",
    "Piculit Neri": "Пикулит Нери",
    "Tintilia": "Тинтилия",
    "Lacrima di Morro": "Лакрима ди Морро",
    "Colorino": "Колорино",
    "Ruchè": "Руке",
    "Grignolino": "Гриньолино",
    "Alfrocheiro": "Алфрокейру",
    "Jampal": "Жампаль",
    "Tamjanika": "Тамьяника",
    "Melnik": "Мелник",
    "Saperavi Budeshuriseburi": "Саперави Будешурисебури",


    # Стили вина
    'French Champagne': "Французское шампанское",
    "Chilean Cabernet Sauvignon": "Чилийский Каберне Совиньон",
    "Spanish Cava": "Испанское Кава",
    "Spanish Grenache": "Испанский Гренаш",
    "Upper Loire White": "Белое Верхней Луары",
    "Spanish Verdejo": "Испанский Вердехо",
    "Tuscan Red": "Тосканское красное",
    "Croatian Dalmatian Coast Plavac Mali Red": "Хорватский красный Плавац Мали (Далмация)",
    "Argentinian Malbec": "Аргентинский Мальбек",
    "Californian Cabernet Sauvignon": "Калифорнийский Каберне Совиньон",
    "Central Italy Red": "Красное Центральной Италии",
    "Spanish Red": "Испанское красное",
    "Argentinian Cabernet Sauvignon - Malbec": "Аргентинский купаж Каберне Совиньон - Мальбек",
    "Bordeaux Blend": "Бордоский бленд",
    "GSM Blend": "Купаж GSM (Гренаш-Сира-Мурведр)",
    "Napa Valley Cabernet": "Каберне из долины Напа",
    "Barolo": "Бароло",
    "Barbaresco": "Барбареско",
    "Chianti Classico": "Кьянти Классико",
    "Brunello di Montalcino": "Брунелло ди Монтальчино",
    "Rioja Reserva": "Риоха Резерва",
    "Ribera del Duero": "Рибера дель Дуэро",
    "Priorat": "Приорат",
    "Douro Red": "Красное Дору",
    "Amarone": "Амароне",
    "Burgundy Chardonnay": "Бургундский Шардоне",
    "Sancerre": "Сансер",
    "Pouilly-Fumé": "Пюи-Фюме",
    "Alsace Riesling": "Эльзасский Рислинг",
    "German Kabinett": "Немецкое Кабинетт",
    "Austrian Grüner Veltliner": "Австрийский Грюнер Вельтлинер",
    "Franciacorta": "Франчакорта",
    "Prosecco": "Просекко",
    "Cava": "Кава",
    "Crémant": "Креман",
    "Orange Wine": "Оранжевое вино",
    "Natural Wine": "Натуральное вино",
    "Ice Wine": "Айсвайн",
    "Port": "Портвейн",
    "Sherry": "Херес",
    "Madeira": "Мадера",
    "Australian Shiraz": "Австралийский Шираз",
    "Hunter Valley Semillon": "Семильон из Хантер Вэлли",
    "Washington Syrah": "Сира из Вашингтона",
    "Stellenbosch Cabernet": "Каберне из Стелленбоша",
    "Chenin Blanc from Swartland": "Шенен Блан из Свартленда",
    "Spanish White": "Испанское белое",
    "Spanish Rosé": "Испанское розовое",
    "Spanish Sparkling": "Испанское игристое",
    "Spanish Dessert": "Испанское десертное",
    "Spanish Fortified": "Испанское креплёное",
    "Spanish Rioja Red": "Риоха — красное вино",
    "Spanish Rioja White": "Риоха — белое вино",
    "Spanish Ribera del Duero Red": "Рибера-дель-Дуэро — красное вино",
    "Spanish Priorat Red": "Приорат — красное вино",
    "Spanish Toro Red": "Торо — красное вино",
    "Spanish Navarra Rosé": "Наварра — розовое вино",
    "Spanish Albariño": "Альбариньо — белое вино",
    "Spanish Tempranillo": "Темпранильо — красное вино",
    "Spanish Garnacha": "Гарнача — красное вино",
    "Spanish Sherry": "Херес — креплёное вино",
    "Spanish Montilla-Moriles": "Монтилья-Морилес — креплёное вино",
    "Spanish Godello": "Годельо — белое вино",
    "Spanish Mencía": "Менсия — красное вино",
    "Spanish Palomino": "Паломино — креплёное вино",
    "Spanish Moscatel": "Москатель — десертное вино",
    "Argentinian Red": "Аргентинское красное",
    "Argentinian White": "Аргентинское белое",
    "Argentinian Rosé": "Аргентинское розовое",
    "Argentinian Sparkling": "Аргентинское игристое",
    "Argentinian Dessert": "Аргентинское десертное",
    "Argentinian Cabernet Sauvignon": "Каберне Совиньон — красное вино",
    "Argentinian Bonarda": "Бонарда — красное вино",
    "Argentinian Syrah": "Сира — красное вино",
    "Argentinian Pinot Noir": "Пино Нуар — красное вино",
    "Argentinian Torrontés": "Торронтес — ароматное белое вино",
    "Argentinian Chardonnay": "Шардоне — белое вино",
    "Argentinian Sauvignon Blanc": "Совиньон Блан — белое вино",
    "Argentinian Mendoza Red": "Мендоса — красное вино",
    "Argentinian Mendoza White": "Мендоса — белое вино",
    "Argentinian Patagonia Red": "Патагония — красное вино",
    "Argentinian Salta Torrontés": "Сальта — Торронтес",
    "Argentinian Sparkling Brut": "Аргентинское игристое брют",
    "Argentinian Extra Brut": "Аргентинское экстра-брют",
    "Argentinian Rosé Sparkling": "Аргентинское розовое игристое",
    "Chilean Red": "Чилийское красное",
    "Chilean White": "Чилийское белое",
    "Chilean Rosé": "Чилийское розовое",
    "Chilean Sparkling": "Чилийское игристое",
    "Chilean Dessert": "Чилийское десертное",
    "Chilean Carménère": "Карменер — фирменное чилийское красное",
    "Chilean Merlot": "Мерло — красное вино",
    "Chilean Syrah": "Сира — насыщенное красное вино",
    "Chilean Pinot Noir": "Пино Нуар — элегантное красное вино",
    "Chilean Sauvignon Blanc": "Совиньон Блан — белое вино",
    "Chilean Chardonnay": "Шардоне — белое вино",
    "Chilean Riesling": "Рислинг — белое вино с яркой кислотностью",
    "Chilean Central Valley Red": "Красное из Центральной долины",
    "Chilean Maipo Valley Red": "Красное из долины Майпо",
    "Chilean Colchagua Valley Red": "Красное из долины Кольчагуа",
    "Chilean Casablanca Valley White": "Белое из долины Касабланка",
    "Chilean Limarí Valley Chardonnay": "Шардоне из долины Лимари",
    "Chilean Sparkling Brut": "Чилийское игристое брют",
    "Chilean Rosé Sparkling": "Чилийское розовое игристое",
    "Bordeaux Red": "Бордо красное",
    "Bordeaux White": "Бордо белое",
    "Burgundy Red": "Бургундия красное",
    "Burgundy White": "Бургундия белое",
    "Beaujolais": "Божоле",
    "Chablis": "Шабли",
    "Côtes du Rhône Red": "Кот-дю-Рон красное",
    "Côtes du Rhône White": "Кот-дю-Рон белое",
    "Loire Sauvignon Blanc": "Луарский Совиньон Блан",
    "Loire Chenin Blanc": "Луарский Шенен Блан",
    "Loire Rosé": "Луарское розовое",
    "Alsace Gewürztraminer": "Эльзасский Гевюрцтраминер",
    "Provence Rosé": "Прованское розовое",
    "Languedoc Red": "Лангедок красное",
    "Languedoc White": "Лангедок белое",
    "Southern Rhône GSM Blend": "Южноронское купаж GSM",
    "Champagne": "Шампань",
    "Sauternes": "Сотерн",
    "French Sparkling": "Французское игристое",
    "French Dessert Wine": "Французское десертное вино",
    "French Rosé": "Французское розовое",
    "French Pinot Noir": "Французский Пино Нуар",
    "French Cabernet Sauvignon": "Французский Каберне Совиньон",
    "French Chardonnay": "Французский Шардоне",
    "French Syrah": "Французский Сира",
    "French Merlot": "Французский Мерло",
    "French Sauvignon Blanc": "Французский Совиньон Блан",
    "French Malbec": "Французский Мальбек",
    "Chianti": "Кьянти",
    "Montepulciano d'Abruzzo": "Монтепульчано д'Абруццо",
    "Valpolicella": "Вальполичелла",
    "Super Tuscan": "Супер Тосканское",
    "Sangiovese": "Санджовезе",
    "Nebbiolo": "Неббиоло",
    "Pinot Grigio": "Пино Гриджио",
    "Gavi": "Гави",
    "Soave": "Соаве",
    "Vermentino": "Верментино",
    "Greco di Tufo": "Греко ди Туфо",
    "Frascati": "Фраскати",
    "Moscato d'Asti": "Москато д'Асти",
    "Lambrusco": "Ламбруско",
    "Trento DOC": "Тренто DOC",
    "Italian Sparkling": "Итальянское игристое",
    "Italian Dessert Wine": "Итальянское десертное",
    "Italian Rosé": "Итальянское розовое",
    "Spätburgunder": "Шпетбургундер",
    "Silvaner": "Зильванер",
    "Grauburgunder": "Граубургундер",
    "Weissburgunder": "Вайсбургундер",
    "Dornfelder": "Дорнфельдер",
    "Müller-Thurgau": "Мюллер-Тургау",
    "Trollinger": "Троллингер",
    "Lemberger": "Лембергер",
    "Elbling": "Эльблинг",
    "Kerner": "Кернер",
    "Bacchus": "Бахус",
    "German Rosé": "Немецкое розовое",
    "German Sparkling (Sekt)": "Немецкое игристое (Зект)",
    "German Dessert Wine": "Немецкое десертное вино",
    "Eiswein": "Айсвайн",
    "Kabinett": "Кабинет",
    "Spätlese": "Шпетлезе",
    "Auslese": "Ауслезе",
    "Beerenauslese": "Берен-ауслезе",
    "Trockenbeerenauslese": "Трокенберенауслезе",
    "Qualitätswein": "Квалифицированное вино (QbA)",
    "Prädikatswein": "Предикатное вино",
    "California Cabernet Sauvignon": "Калифорнийский Каберне Совиньон",
    "California Chardonnay": "Калифорнийское Шардоне",
    "California Zinfandel": "Калифорнийский Зинфандель",
    "California Pinot Noir": "Калифорнийский Пино Нуар",
    "California Merlot": "Калифорнийский Мерло",
    "California Syrah": "Калифорнийский Сира",
    "California Sauvignon Blanc": "Калифорнийский Совиньон Блан",
    "Oregon Pinot Noir": "Орегонский Пино Нуар",
    "Washington Cabernet Sauvignon": "Вашингтонский Каберне Совиньон",
    "Washington Merlot": "Вашингтонский Мерло",
    "Napa Valley Red Blend": "Купаж красных вин Напа Вэлли",
    "Napa Valley Cabernet Sauvignon": "Каберне Совиньон из Напа Вэлли",
    "Sonoma Chardonnay": "Шардоне из Сономы",
    "Columbia Valley Red Blend": "Купаж красных вин из Колумбийской долины",
    "American Rosé": "Американское розовое вино",
    "American Sparkling Wine": "Американское игристое вино",
    "American Dessert Wine": "Американское десертное вино",
    "California Petite Sirah": "Калифорнийский Пти Сира",
    "American Riesling": "Американский Рислинг",
    "California Red Blend": "Калифорнийский красный купаж",
    "Australian Cabernet Sauvignon": "Австралийский Каберне Совиньон",
    "Australian Chardonnay": "Австралийское Шардоне",
    "Australian Sauvignon Blanc": "Австралийский Совиньон Блан",
    "Australian Merlot": "Австралийский Мерло",
    "Australian Pinot Noir": "Австралийский Пино Нуар",
    "Barossa Valley Shiraz": "Шираз из долины Баросса",
    "McLaren Vale Red Blend": "Красный купаж из Макларен Вейл",
    "Clare Valley Riesling": "Рислинг из долины Клэр",
    "Yarra Valley Pinot Noir": "Пино Нуар из долины Ярра",
    "Margaret River Cabernet Sauvignon": "Каберне Совиньон из Маргарет Ривер",
    "Coonawarra Cabernet Sauvignon": "Каберне Совиньон из Кунаварры",
    "Australian Sparkling Wine": "Австралийское игристое вино",
    "Australian Rosé": "Австралийское розовое вино",
    "Australian Dessert Wine": "Австралийское десертное вино",
    "Australian Fortified Wine": "Австралийское крепленое вино",
    "New Zealand Sauvignon Blanc": "Новозеландский Совиньон Блан",
    "New Zealand Pinot Noir": "Новозеландский Пино Нуар",
    "New Zealand Chardonnay": "Новозеландское Шардоне",
    "New Zealand Riesling": "Новозеландский Рислинг",
    "New Zealand Pinot Gris": "Новозеландский Пино Гри",
    "New Zealand Merlot": "Новозеландский Мерло",
    "New Zealand Syrah": "Новозеландский Сира",
    "New Zealand Sparkling Wine": "Новозеландское игристое вино",
    "New Zealand Rosé": "Новозеландское розовое вино",
    "New Zealand Dessert Wine": "Новозеландское десертное вино",
    "Marlborough Sauvignon Blanc": "Совиньон Блан из Мальборо",
    "Central Otago Pinot Noir": "Пино Нуар из Центрального Отаго",
    "Hawke's Bay Merlot Blend": "Купаж Мерло из Хокс-Бей",
    "Waipara Valley Riesling": "Рислинг из долины Уайпара",
    "Gisborne Chardonnay": "Шардоне из Гисборна",
    "South African Chenin Blanc": "Южноафриканский Шенен Блан",
    "South African Pinotage": "Южноафриканский Пинотаж",
    "South African Sauvignon Blanc": "Южноафриканский Совиньон Блан",
    "South African Cabernet Sauvignon": "Южноафриканский Каберне Совиньон",
    "South African Syrah": "Южноафриканский Сира",
    "South African Merlot": "Южноафриканский Мерло",
    "South African Chardonnay": "Южноафриканское Шардоне",
    "South African Red Blend": "Южноафриканский красный купаж",
    "South African White Blend": "Южноафриканский белый купаж",
    "South African Sparkling Wine": "Южноафриканское игристое вино",
    "South African Rosé": "Южноафриканское розовое вино",
    "South African Dessert Wine": "Южноафриканское десертное вино",
    "Stellenbosch Cabernet Sauvignon": "Каберне Совиньон из Стелленбоша",
    "Swartland Syrah": "Сира из Свартленда",
    "Constantia Sweet Wine": "Сладкое вино из Констанции",
    "Walker Bay Pinot Noir": "Пино Нуар из Уокер Бэй",
    "Portuguese Red": "Португальское красное вино",
    "Portuguese White": "Португальское белое вино",
    "Portuguese Rosé": "Португальское розовое вино",
    "Vinho Verde": "Винью Верде",
    "Douro White": "Белое вино из Дору",
    "Alentejo Red": "Красное вино из Алентежу",
    "Alentejo White": "Белое вино из Алентежу",
    "Dao Red": "Красное вино из Дао",
    "Dao White": "Белое вино из Дао",
    "Bairrada Red": "Красное вино из Байррады",
    "Bairrada Sparkling": "Игристое вино из Байррады",
    "Lisboa Red": "Красное вино из Лиссабона",
    "Setúbal Muscat": "Мускат из Сетубала",
    "White Port": "Белый портвейн",
    "Tawny Port": "Тони портвейн",
    "Ruby Port": "Руби портвейн",
    "Late Bottled Vintage Port": "Поздний бутылочный винтажный портвейн",
    "Vintage Port": "Винтажный портвейн",
    "Greek Red": "Греческое красное вино",
    "Greek White": "Греческое белое вино",
    "Greek Rosé": "Греческое розовое вино",
    "Agiorgitiko": "Агиоргитико",
    "Roditis": "Родитис",
    "Malagousia": "Малагузия",
    "Retsina": "Рецина",
    "Santorini White": "Белое вино Санторини",
    "Naoussa Red": "Красное вино Наусса",
    "Nemea Red": "Красное вино Немеи",
    "Crete Red": "Красное вино Крита",
    "Crete White": "Белое вино Крита",
    "Sweet Muscat": "Сладкий мускат",
    "Vinsanto": "Винсанто",
    "Georgian Red": "Грузинское красное вино",
    "Georgian White": "Грузинское белое вино",
    "Kindzmarauli": "Киндзмараули",
    "Mukuzani": "Мукузани",
    "Khvanchkara": "Хванчкара",
    "Tsinandali": "Цинандали",
    "Qvevri Wine": "Вино в квеври",
    "Amber Wine": "Янтарное вино",
    "Georgian Rosé": "Грузинское розовое вино",
    "Akhasheni": "Ахашени",
    "Tvishi": "Твиши",
    "Ojaleshi": "Оджалеши",
    "Austrian Red": "Австрийское красное вино",
    "Austrian White": "Австрийское белое вино",
    "Zweigelt": "Цвайгельт",
    "St. Laurent": "Санкт-Лаурент",
    "Welschriesling": "Вельшрислинг",
    "Gemischter Satz": "Гемиштер Сац",
    "Austrian Rosé": "Австрийское розовое вино",
    "Ausbruch": "Аусбрух",
    "Smaragd": "Смарагд",
    "Steinfeder": "Штайнфедер",
    "Federspiel": "Федершпиль",
    "Armenian Red": "Армянское красное вино",
    "Armenian White": "Армянское белое вино",
    "Areni": "Арени",
    "Voskehat": "Воскеат",
    "Kangun": "Кангун",
    "Haghtanak": "Ахтанак",
    "Khndoghni / Sireni": "Хндогни / Сирени",
    "Armenian Rosé": "Армянское розовое вино",
    "Armenian Sparkling": "Армянское игристое вино",
    "Areni Noir": "Арени Нуар",
    "Karas Wine": "Вино Карас",
    "Qvevri-style Armenian Wine": "Армянское вино в стиле квеври",
    "Armenian Dessert Wine": "Армянское десертное вино",
    "Lykhny": "Лыхны",
    "Apsny": "Апсны",
    "Psou": "Псоу",
    "Chegem": "Чегем",
    "Anakopia": "Анакопия",
    "Eshera": "Эшера",
    "Amra": "Амра",
    "Abyata": "Абьята",
    "Ayuaa": "Аюаа",
    "Abkhazia Red": "Абхазское красное вино",
    "Abkhazia White": "Абхазское белое вино",
    "Abkhazia Semi-sweet Red": "Абхазское полусладкое красное",
    "Abkhazia Semi-sweet White": "Абхазское полусладкое белое",
    "Massandra Port": "Портвейн Массандра",
    "Massandra Muscat": "Мускат Массандра",
    "Black Doctor": "Чёрный доктор",
    "White Muscat of Red Stone": "Белый мускат красного камня",
    "Bastardo Magarachsky": "Бастардо Магарачский",
    "Kagor Yubileyny": "Кагор Юбилейный",
    "Crimean Cabernet": "Крымский Каберне",
    "Alushta": "Алушта",
    "Saperavi Crimean": "Саперави Крымское",
    "Pinot Noir Crimean": "Пино Нуар Крымский",
    "Chardonnay Crimean": "Шардоне Крымское",
    "Muscat Crimean": "Мускат Крымский",
    "Riesling Crimean": "Рислинг Крымский",
    "Crimean Sparkling": "Крымское игристое",
    "Novy Svet Brut": "Новый Свет Брют",
    "Soviet Sparkling Wine (Crimea)": "Советское шампанское (Крым)",
    "Magarach Dessert": "Десертное Магарач",
    "Livadia White": "Ливадия Белое",
    "Ai-Danil": "Ай-Даниль",
    "Crimean Red Blend": "Крымский купаж красного вина",
    "Crimean White Blend": "Крымский купаж белого вина",
    "Russian Red": "Российское красное",
    "Russian White": "Российское белое",
    "Russian Rosé": "Российское розовое",
    "Russian Sparkling": "Российское игристое",
    "Russian Semi-Sweet": "Российское полусладкое",
    "Russian Semi-Dry": "Российское полусухое",
    "Russian Sweet Red": "Российское десертное красное",
    "Russian Dessert Wine": "Российское десертное вино",
    "Fanagoria Cabernet": "Фанагория Каберне",
    "Fanagoria Merlot": "Фанагория Мерло",
    "Fanagoria Riesling": "Фанагория Рислинг",
    "Kuban Red": "Кубанское красное",
    "Kuban White": "Кубанское белое",
    "Lefkadia Valley Red": "Лефкадия красное",
    "Lefkadia Valley White": "Лефкадия белое",
    "Usadba Divnomorskoe": "Усадьба Дивноморское",
    "Abrau-Durso Brut": "Абрау-Дюрсо Брют",
    "Ukrainian Red": "Красное",
    "Ukrainian White": "Белое",
    "Abrau-Durso Rosé": "Абрау-Дюрсо Розовое",
    "Abrau-Durso Semi-Sweet": "Абрау-Дюрсо Полусладкое",
    "Russian Ice Wine": "Российское ледяное вино",
    "Tsimlyansk Sparkling": "Цимлянское игристое",
    "Don Red": "Донское красное",
    "Don Cuvée": "Кюве Дона",
    "Vedernikov Krasnostop Zolotovsky": "Красностоп Золотовский Ведерниковъ",
    "Saperavi Russian": "Саперави Российский",
    "Russian Krasnostop": "Российское вино из сорта Красностоп",
    "Russian Sibirkovy": "Российское вино из сорта Сибирьковый",
    "Russian Tsimlyansky Black": "Российское вино из сорта Цимлянский черный",
    "Russian Plechistik": "Российское вино из сорта Плечистик",
    "Russian Rubinovy Magarach": "Российское вино из сорта Рубиновый Массандра",
    "Russian Golubok": "Российское вино из сорта Голубок",
    "Russian Bastardo Magarachsky": "Российское вино из сорта Бастардо Магаарачский",
    "Russian Kokur": "Российское вино из сорта Кокур",
    "Russian Saperavi Severny": "Российское вино из сорта Саперави Северный",
    "Russian Saperavi": "Российское Саперави",
    "Russian Cabernet": "Российское Каберне",
    "Russian Merlot": "Российское Мерло",
    "Russian Muscat": "Российский Мускат",
    "Russian Chardonnay": "Российское Шардоне",
    "Russian Riesling": "Российский Рислинг",
    "Russian Pinot Noir": "Российский Пино Нуар",
    "Russian Fortified Wine": "Российское креплёное вино",
    "Russian Semi-sweet Red": "Российское полусладкое красное",
    "Russian Semi-sweet White": "Российское полусладкое белое",
}

REGION_TRANSLATIONS = {
    "Spain": "Испания",
    "Rioja": "Риоха",
    "Ribera del Duero": "Рибера-дель-Дуэро",
    "Catalonia": "Каталония",
    "Valencia": "Валенсия",
    "Castilla-La Mancha": "Кастилия-Ла-Манча",
    "Galicia": "Галисия",
    "Andalusia": "Андалусия",
    "Navarra": "Наварра",

    "France": "Франция",
    "Bordeaux": "Бордо",
    "Burgundy": "Бургундия",
    "Champagne": "Шампань",
    "Loire Valley": "Долина Луары",
    "Alsace": "Эльзас",
    "Rhone Valley": "Долина Роны",
    "Languedoc-Roussillon": "Лангедок-Руссильон",
    "Provence": "Прованс",

    "Italy": "Италия",
    "Tuscany": "Тоскана",
    "Piedmont": "Пьемонт",
    "Veneto": "Венето",
    "Sicily": "Сицилия",
    "Lombardy": "Ломбардия",
    "Trentino-Alto Adige": "Трентино-Альто-Адидже",
    "Emilia-Romagna": "Эмилия-Романья",

    "Germany": "Германия",
    "Mosel": "Мозель",
    "Rheingau": "Рейнгау",
    "Pfalz": "Пфальц",
    "Baden": "Баден",

    "USA": "США",
    "California": "Калифорния",
    "Napa Valley": "Напа Вэлли",
    "Sonoma": "Сонома",
    "Washington": "Вашингтон",
    "Oregon": "Орегон",

    "Argentina": "Аргентина",
    "Mendoza": "Мендоса",
    "Patagonia": "Патагония",
    "Salta": "Сальта",

    "Chile": "Чили",
    "Central Valley": "Центральная долина",
    "Maipo Valley": "Маипо",
    "Colchagua Valley": "Кольчагуа",
    "Casablanca Valley": "Касабланка",

    "South Africa": "ЮАР",
    "Stellenbosch": "Стелленбош",
    "Paarl": "Паарл",
    "Walker Bay": "Уокер Бэй",

    "Australia": "Австралия",
    "Barossa Valley": "Долина Баросса",
    "McLaren Vale": "Макларен Вейл",
    "Yarra Valley": "Долина Ярра",

    "Portugal": "Португалия",
    "Douro": "Дору",
    "Alentejo": "Алентежу",
    "Vinho Verde": "Винью Верде",

    "Georgia": "Грузия",
    "Kakheti": "Кахетия",
    "Imereti": "Имерети",
    "Racha": "Рача",
    "Kartli": "Картли",

    "Russia": "Россия",
    "Kuban": "Кубань",
    "Don": "Дон",
    "Don Valley": "Долина Дона",
    "Crimea": "Крым",
    "Taman": "Тамань",
    "Taman Peninsula": "Полуостров Тамань",
    "Anapa": "Анапа",
    "Sennoi": "п. Сенной",
    "Gelendzhik": "Геленджик",

    "Abkhazia": "Абхазия",
    "Gudauta": "Гудаута",
    "Sukhum": "Сухум",
    "Gagra": "Гагра",

    "Armenia": "Армения",
    "Vayots Dzor": "Вайоц Дзор",
    "Ararat": "Арарат",
    "Armavir": "Армавир",

    "Austria": "Австрия",
    "Wachau": "Вахау",
    "Burgenland": "Бургенланд",
    "Styria": "Штирия",
}